//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppChart
    {
        public int ChartID { get; set; }
        public int ChartCategoryID { get; set; }
        public string ChartName { get; set; }
        public string ChartDescription { get; set; }
        public string ChartNameX { get; set; }
        public string ChartDescriptionX { get; set; }
    
        public virtual AppChartCategory AppChartCategory { get; set; }
    }
}
