//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppChartCategory
    {
        public AppChartCategory()
        {
            this.AppCharts = new HashSet<AppChart>();
        }
    
        public int ChartCategoryID { get; set; }
        public string ChartCategory { get; set; }
        public string ChartCategoryX { get; set; }
    
        public virtual ICollection<AppChart> AppCharts { get; set; }
    }
}
