//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppModule
    {
        public AppModule()
        {
            this.AppPermissions = new HashSet<AppPermission>();
            this.AppRoleModules = new HashSet<AppRoleModule>();
        }
    
        public int ModuleID { get; set; }
        public string Module { get; set; }
        public string ModuleX { get; set; }
    
        public virtual ICollection<AppPermission> AppPermissions { get; set; }
        public virtual ICollection<AppRoleModule> AppRoleModules { get; set; }
    }
}
