//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppPermission
    {
        public AppPermission()
        {
            this.AppRolePermissions = new HashSet<AppRolePermission>();
        }
    
        public int PermissionID { get; set; }
        public string Permission { get; set; }
        public string PermissionX { get; set; }
        public string Description { get; set; }
        public string DescriptionX { get; set; }
        public int ModuleID { get; set; }
    
        public virtual AppModule AppModule { get; set; }
        public virtual ICollection<AppRolePermission> AppRolePermissions { get; set; }
    }
}
