//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppRolePermission
    {
        public int EntryID { get; set; }
        public System.Guid RoleID { get; set; }
        public int PermissionID { get; set; }
    
        public virtual AppPermission AppPermission { get; set; }
        public virtual AppRole AppRole { get; set; }
    }
}
