//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserProfile
    {
        public int ProfileID { get; set; }
        public System.Guid UserID { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
