//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserInfo
    {
        public System.Guid UserID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EMailAddress { get; set; }
        public string PhoneNumbers { get; set; }
    
        public virtual AppUserCompany AppUserCompany { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
