//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserCompany
    {
        public AppUserCompany()
        {
            this.AppUserInfos = new HashSet<AppUserInfo>();
            this.AppUsers = new HashSet<AppUser>();
        }
    
        public System.Guid CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyShortName { get; set; }
        public string CompanyAddress { get; set; }
    
        public virtual ICollection<AppUserInfo> AppUserInfos { get; set; }
        public virtual ICollection<AppUser> AppUsers { get; set; }
    }
}
