//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VaultsEntities : DbContext
    {
        public VaultsEntities()
            : base("name=VaultsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppChartCategory> AppChartCategories { get; set; }
        public virtual DbSet<AppChart> AppCharts { get; set; }
        public virtual DbSet<AppModule> AppModules { get; set; }
        public virtual DbSet<AppPermission> AppPermissions { get; set; }
        public virtual DbSet<AppPicture> AppPictures { get; set; }
        public virtual DbSet<AppRoleModule> AppRoleModules { get; set; }
        public virtual DbSet<AppRolePermission> AppRolePermissions { get; set; }
        public virtual DbSet<AppRole> AppRoles { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<AppStaff> AppStaffs { get; set; }
        public virtual DbSet<AppUserCompany> AppUserCompanies { get; set; }
        public virtual DbSet<AppUserCredential> AppUserCredentials { get; set; }
        public virtual DbSet<AppUserInfo> AppUserInfos { get; set; }
        public virtual DbSet<AppUserProfile> AppUserProfiles { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<DeviceType> DeviceTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VaultAmountQuantity> VaultAmountQuantities { get; set; }
        public virtual DbSet<VaultAmount> VaultAmounts { get; set; }
        public virtual DbSet<VaultAmountType> VaultAmountTypes { get; set; }
        public virtual DbSet<VaultCashOrderQuantity> VaultCashOrderQuantities { get; set; }
        public virtual DbSet<VaultCashOrder> VaultCashOrders { get; set; }
        public virtual DbSet<VaultCashOrderStatus> VaultCashOrderStatuses { get; set; }
        public virtual DbSet<VaultCashPoint> VaultCashPoints { get; set; }
        public virtual DbSet<VaultCurrency> VaultCurrencies { get; set; }
        public virtual DbSet<VaultCurrencyDenomination> VaultCurrencyDenominations { get; set; }
        public virtual DbSet<VaultEventAmount> VaultEventAmounts { get; set; }
        public virtual DbSet<VaultEventQuantity> VaultEventQuantities { get; set; }
        public virtual DbSet<VaultEvent> VaultEvents { get; set; }
        public virtual DbSet<VaultEventType> VaultEventTypes { get; set; }
        public virtual DbSet<VaultNetworkNode> VaultNetworkNodes { get; set; }
        public virtual DbSet<VaultNetworkNodeType> VaultNetworkNodeTypes { get; set; }
        public virtual DbSet<VaultRecepient> VaultRecepients { get; set; }
        public virtual DbSet<Vault> Vaults { get; set; }
        public virtual DbSet<VaultServiceCompany> VaultServiceCompanies { get; set; }
        public virtual DbSet<VaultType> VaultTypes { get; set; }
    }
}
