//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultCurrencyDenomination
    {
        public VaultCurrencyDenomination()
        {
            this.VaultAmountQuantities = new HashSet<VaultAmountQuantity>();
            this.VaultCashOrderQuantities = new HashSet<VaultCashOrderQuantity>();
            this.VaultEventQuantities = new HashSet<VaultEventQuantity>();
        }
    
        public int VaultCurrencyDenominationId { get; set; }
        public string DenominationName { get; set; }
        public int Denomination { get; set; }
        public int VaultCurrencyId { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual ICollection<VaultAmountQuantity> VaultAmountQuantities { get; set; }
        public virtual ICollection<VaultCashOrderQuantity> VaultCashOrderQuantities { get; set; }
        public virtual VaultCurrency VaultCurrency { get; set; }
        public virtual ICollection<VaultEventQuantity> VaultEventQuantities { get; set; }
    }
}
