//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultServiceCompany
    {
        public VaultServiceCompany()
        {
            this.VaultEvents = new HashSet<VaultEvent>();
            this.Vaults = new HashSet<Vault>();
        }
    
        public int VaultServiceCompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyShortName { get; set; }
        public string CompanyAddress { get; set; }
    
        public virtual ICollection<VaultEvent> VaultEvents { get; set; }
        public virtual ICollection<Vault> Vaults { get; set; }
    }
}
