//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultEvent
    {
        public VaultEvent()
        {
            this.VaultAmounts = new HashSet<VaultAmount>();
            this.VaultEventAmounts = new HashSet<VaultEventAmount>();
            this.VaultEventQuantities = new HashSet<VaultEventQuantity>();
        }
    
        public System.Guid VaultEventId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid DeviceId { get; set; }
        public Nullable<System.Guid> SecondDeviceId { get; set; }
        public Nullable<int> SecondDeviceTypeId { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public System.DateTime EventDate { get; set; }
        public int NumberIncrement { get; set; }
        public int VaultServiceCompanyId { get; set; }
        public string DeviceAddress { get; set; }
        public int VaultEventTypeId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> PreviousEventId { get; set; }
        public string FriendlyName { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
        public virtual ICollection<VaultAmount> VaultAmounts { get; set; }
        public virtual ICollection<VaultEventAmount> VaultEventAmounts { get; set; }
        public virtual ICollection<VaultEventQuantity> VaultEventQuantities { get; set; }
        public virtual VaultServiceCompany VaultServiceCompany { get; set; }
        public virtual VaultEventType VaultEventType { get; set; }
        public virtual Vault Vault { get; set; }
    }
}
