//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultType
    {
        public VaultType()
        {
            this.Vaults = new HashSet<Vault>();
        }
    
        public int VaultTypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Vault> Vaults { get; set; }
    }
}
