//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultAmount
    {
        public VaultAmount()
        {
            this.VaultAmountQuantities = new HashSet<VaultAmountQuantity>();
        }
    
        public System.Guid VaultAmountId { get; set; }
        public System.Guid VaultId { get; set; }
        public int VaultCurrencyId { get; set; }
        public bool IsCurrent { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> VaultEventId { get; set; }
        public decimal VaultRemainder { get; set; }
        public decimal CashInTransitIn { get; set; }
        public decimal CashInTransitInReserved { get; set; }
        public decimal CashInTransitSent { get; set; }
        public decimal CashInTransitInPlan { get; set; }
        public decimal CashInTransitOut { get; set; }
        public decimal CashInTransitOutReserved { get; set; }
        public decimal CashInTransitOutSent { get; set; }
        public decimal CashInNet { get; set; }
        public decimal GrandTotal { get; set; }
        public System.DateTime VaultAmountDateTime { get; set; }
    
        public virtual ICollection<VaultAmountQuantity> VaultAmountQuantities { get; set; }
        public virtual VaultEvent VaultEvent { get; set; }
        public virtual VaultCurrency VaultCurrency { get; set; }
        public virtual Vault Vault { get; set; }
    }
}
