//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultEventAmount
    {
        public System.Guid VaultEventAmountId { get; set; }
        public System.Guid VaultEventId { get; set; }
        public int VaultCurrencyId { get; set; }
        public decimal Amount { get; set; }
        public double ExchangeRateToBaseCurrency { get; set; }
        public decimal AmountBaseCurrency { get; set; }
    
        public virtual VaultCurrency VaultCurrency { get; set; }
        public virtual VaultEvent VaultEvent { get; set; }
    }
}
