//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultEventType
    {
        public VaultEventType()
        {
            this.VaultEvents = new HashSet<VaultEvent>();
        }
    
        public int VaultEventTypeId { get; set; }
        public string EventType { get; set; }
    
        public virtual ICollection<VaultEvent> VaultEvents { get; set; }
    }
}
