//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultNetworkNodeType
    {
        public VaultNetworkNodeType()
        {
            this.VaultNetworkNodes = new HashSet<VaultNetworkNode>();
        }
    
        public int VaultNodeTypeId { get; set; }
        public int VaultNodeCategoryId { get; set; }
        public string VaultNodeType { get; set; }
    
        public virtual ICollection<VaultNetworkNode> VaultNetworkNodes { get; set; }
    }
}
