//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultNetworkNode
    {
        public int EntryId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ParentId { get; set; }
        public System.Guid VaultNodeId { get; set; }
        public int VaultNodeTypeId { get; set; }
        public System.Guid DeviceId { get; set; }
        public string VaultNodeName { get; set; }
        public bool IsActive { get; set; }
        public bool IsAssigned { get; set; }
        public int SortOrder { get; set; }
        public int NodeCount { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> ZoomLevel { get; set; }
    
        public virtual VaultNetworkNodeType VaultNetworkNodeType { get; set; }
    }
}
