//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultAmountType
    {
        public VaultAmountType()
        {
            this.VaultAmountQuantities = new HashSet<VaultAmountQuantity>();
        }
    
        public int VaultAmountTypeId { get; set; }
        public string AmountType { get; set; }
    
        public virtual ICollection<VaultAmountQuantity> VaultAmountQuantities { get; set; }
    }
}
