//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultCashOrderStatus
    {
        public VaultCashOrderStatus()
        {
            this.VaultCashOrders = new HashSet<VaultCashOrder>();
        }
    
        public int VaultCashOrderStatusId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<VaultCashOrder> VaultCashOrders { get; set; }
    }
}
