//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplicationTest.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultCurrency
    {
        public VaultCurrency()
        {
            this.VaultAmountQuantities = new HashSet<VaultAmountQuantity>();
            this.VaultAmounts = new HashSet<VaultAmount>();
            this.VaultCashOrderQuantities = new HashSet<VaultCashOrderQuantity>();
            this.VaultCurrencyDenominations = new HashSet<VaultCurrencyDenomination>();
            this.VaultEventAmounts = new HashSet<VaultEventAmount>();
            this.VaultEventQuantities = new HashSet<VaultEventQuantity>();
        }
    
        public int VaultCurrencyId { get; set; }
        public string VaultCurrencyCode { get; set; }
        public string VaultCurrencyName { get; set; }
        public bool IsBase { get; set; }
        public bool IsUsed { get; set; }
        public float ExchangeRate { get; set; }
        public int SortBy { get; set; }
    
        public virtual ICollection<VaultAmountQuantity> VaultAmountQuantities { get; set; }
        public virtual ICollection<VaultAmount> VaultAmounts { get; set; }
        public virtual ICollection<VaultCashOrderQuantity> VaultCashOrderQuantities { get; set; }
        public virtual ICollection<VaultCurrencyDenomination> VaultCurrencyDenominations { get; set; }
        public virtual ICollection<VaultEventAmount> VaultEventAmounts { get; set; }
        public virtual ICollection<VaultEventQuantity> VaultEventQuantities { get; set; }
    }
}
